import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';

import Providers from '@/utils/Providers';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { Toaster as Sonner } from '@/components/ui/sonner';
import { Toaster } from '@/components/ui/toaster';
import { SessionStoreProvider } from '@/utils/SessionProvider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="light" suppressHydrationWarning>
      <body className={cn('min-h-screen bg-background antialiased', inter.className)}>
        <Providers>
          <SessionStoreProvider>
            <Sonner position="top-center" richColors />
            <Toaster />
            <Header />
            {children}
            <Footer />
          </SessionStoreProvider>
        </Providers>
      </body>
    </html>
  );
}
